// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBQKB0hGoZT6Gvycxf03a3RwMZVxGDKOdM',
    appId: '1:1053519100804:web:d72af90cbac123abf53bd1',
    messagingSenderId: '1053519100804',
    projectId: 'souq-f1f99',
    authDomain: 'souq-f1f99.firebaseapp.com',
    storageBucket: 'souq-f1f99.appspot.com',
    measurementId: 'G-M2EKYTCXY0',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB46hbOlKFAqL8FUkHJL5RYZfM0ksVbo-k',
    appId: '1:1053519100804:android:d2224c772e785d13f53bd1',
    messagingSenderId: '1053519100804',
    projectId: 'souq-f1f99',
    storageBucket: 'souq-f1f99.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBEqvM8zL-8lbtQay0YO3pw2CsW3omrbH0',
    appId: '1:1053519100804:ios:d26ca61f0776c2c5f53bd1',
    messagingSenderId: '1053519100804',
    projectId: 'souq-f1f99',
    storageBucket: 'souq-f1f99.appspot.com',
    iosBundleId: 'com.example.souq',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBEqvM8zL-8lbtQay0YO3pw2CsW3omrbH0',
    appId: '1:1053519100804:ios:af7dced2dd40c5f2f53bd1',
    messagingSenderId: '1053519100804',
    projectId: 'souq-f1f99',
    storageBucket: 'souq-f1f99.appspot.com',
    iosBundleId: 'com.example.souq.RunnerTests',
  );
}
